name: Hardcoded Key Workflow

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python & requests
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install requests

      - name: Run weather.py with hardcoded key
        run: python3 weather.py
