name: Secrets Workflow

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Python & requests
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install requests

      - name: Run weather.py with secret
        run: python3 weather.py
